### ISSUE TITLE
CH7.AmazonSP.py

### ISSUE THREAD

**Issue by sialaichai** [PacktPublishing/Keras-2.x-Projects#2]
Hi,
I followed the book example for LSTM using Amazon.csv file but just could not get the graph on page 232, even with this updated file. The difference between the train and predicted is very big.
Not sure what is the issue. The training is done using google colab python 3 with TPU.

![amazon](https://user-images.githubusercontent.com/19499922/56468699-8f952680-6462-11e9-836e-37972010fc40.jpg)

**Comment by casijoe5231** [comment]
Hey sialaichai, this is a reply for you from the author of the book, Giuseppe:

"Dear reader,
First of all, thank you for purchasing my book. The problem you raised is documented in the random part that is present in each machine-based algorithm, and which has determined its success. This means that turning the program on another program can lead to slightly different results. Furthermore, in the construction of a model based on Machine Learning, the training phase is of fundamental importance and, if it does not lead to good results, it must be repeated several times. Finally, the hot spot of the problem is the adjustment of the parameters. All these features must be balanced by the researcher. To make the example reproducible I inserted the seed, which as explained in my book, makes it so that in the random choice of the parameters it is always the same. Let me know if you need further explanation."

**Comment by casijoe5231** [comment]
I've updated the code file in CH7, please check it out and let me know if this issue has been sorted
